config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root to: "home#top"
  get "about" => "home#about"
  get "terms" => "home#terms"
  get "policy" => "home#policy"
  get "users/:id/favorites" => "users#favorites"
  resources :users
  resources :saunas do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get :search
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :sauna
  validates_uniqueness_of :sauna_id, scope: :user_id
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_sauna

  # お気に入り追加
  def create
    @favorite = Favorite.create(user_id: current_user.id, sauna_id: @sauna.id)
  end

  # お気に入り解除
  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, sauna_id: @sauna.id)
    @favorite.destroy
    redirect_to sauna_path(@sauna) # お気に入りを解除するがリロードしないと★表示が変わらなかったため一旦これで
  end

  private

  def set_sauna
    @sauna = Sauna.find(params[:sauna_id])
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<div class='star-btn' id="favorite_<%= sauna.id %>">
  <% if !Favorite.exists?(user_id: current_user.id, sauna_id: sauna.id) %>
    <%= link_to sauna_favorites_path(sauna.id), method: :post, remote: true, class:"like-btn" do %>
      <i class="far fa-sm fa-star" style="color:gold;"></i>
    <% end %>
    <span class="star-count1"><%= sauna.favorites.count %></span>
  <% else %>
    <%= link_to sauna_favorites_path(sauna.id), method: :delete, remote: true, class: "like-btn" do %>
      <i class="fas fa-sm fa-star" style="color:gold;"></i>
    <% end %>
    <span class="star-count2"><%= sauna.favorites.count %></span>
  <% end %>
</div>

app/views/favorites/create.js.erb
$('#favorite_<%= @sauna.id %>').html("<%= j(render partial: 'favorites/favorite', locals: { sauna: @sauna }) %>");

app/views/favorites/detele.js.erb
$('#favorite_<%= @sauna.id %>').html("<%= j(render partial: 'favorites/favorite', locals: { sauna: @sauna }) %>");