config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root to: "home#top"
  get "about" => "home#about"
  get "terms" => "home#terms"
  get "policy" => "home#policy"
  get "users/:id/favorites" => "users#favorites"
  resources :users
  resources :saunas do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get :search
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @sauna_favorite_ranks = Sauna.find(Favorite.group(:sauna_id).limit(3).order('count(sauna_id) desc').pluck(:sauna_id))
  end

  def about
  end

  def terms
  end

  def policy
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_ranking.html.erb
<div class="container">
	<div class="contents-title text-center">
		<h3 class="index-title">
			人気サウナランキング
		</h3>
	</div>
	<div class="row">
		<% sauna_favorite_ranks.each.with_index(1) do |sauna, i| %>
			<% if sauna.privacy == "1" %>
				<div class="col-md-4">
					<div class="card">
						<% if sauna.avatar.attached? %>
							<%= image_tag sauna.avatar, class: "card-img-top" %>
						<% else %>
							<%= image_tag "no-image.png", class: "card-img-top" %>
						<% end %>
						<div class="card-body text-center">
							<h5>
								<i class="fas fa-medal" style="color: 
									<% if i == 1 %>
										gold
									<% elsif i == 2 %>
										silver
									<% elsif i == 3 %>
										brown
									<% end %>
									;">
								</i>第<%= i %>位
							</h5>
							<h5 class="card-title"><%= sauna.name %></h5>
							<%= link_to "詳細を見る", sauna_path(sauna.id), class: "btn btn-info" %>
						</div>
					</div>
				</div>
			<% end %>
		<% end %>
	</div>
</div> 

app/views/home/about.html.erb
<div class="main-container">
	<div class="about-view">
		<div class="form-area">
			<h2>Sauna&Campとは</h2>
			<h4>施設のサウナはもちろん、テントサウナ施設・テントサウナができるおすすめのスポットをサウナーで共有するアプリです。</h4>
			<p>
				昨今のサウナブームにより、若者を中心にサウナーが増えています。<br>
				しかし首都圏のサウナでは混雑が目立ち平日は首都圏のサウナ施設へ、土日休日は郊外へ行き自然の中テントサウナで整いたい人もいるのではないでしょうか。<br>
				そこで定番の人気サウナ、あまり知られていないけどオススメしたいサウナ、テントサウナをするのに最適な自然スポットなどみなさまのおすすめをぜひシェアしてみましょう。
			</p>
			<% unless user_signed_in? %>
				<%= link_to "登録してみる", new_user_registration_path, class: "btn btn-success" %>
				<%= link_to "ログイン", new_user_session_path, class: "btn btn-success" %>
			<% end %>
		</div>
	</div>
</div>

app/views/home/policy.html.erb
<div class="policy">
	<h3>プライバシーポリシー</h3>
	<p>Sauna&Camp（以下，「当社」といいます。）は，本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。</p>
	<h4>第1条（個人情報）</h4>
	<p>「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報及び容貌，指紋，声紋にかかるデータ，及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。</p>
	<h4>第2条（個人情報の収集方法）</h4>
	<p>当社は，ユーザーが利用登録をする際に氏名，生年月日，住所，電話番号，メールアドレス，銀行口座番号，クレジットカード番号，運転免許証番号などの個人情報をお尋ねすることがあります。また，ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や決済に関する情報を,当社の提携先（情報提供元，広告主，広告配信先などを含みます。以下，｢提携先｣といいます。）などから収集することがあります。</p>
	<h4>第3条（個人情報を収集・利用する目的）</h4>
	<p>当社が個人情報を収集・利用する目的は，以下のとおりです。</p>
		<ul class="hierarchy">
			<li>1. 当社サービスの提供・運営のため</li>
			<li>2. ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）</li>
			<li>3. ユーザーが利用中のサービスの新機能，更新情報，キャンペーン等及び当社が提供する他のサービスの案内のメールを送付するため</li>
			<li>4. メンテナンス，重要なお知らせなど必要に応じたご連絡のため</li>
			<li>5. 利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの特定をし，ご利用をお断りするため</li>
			<li>6. ユーザーにご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため</li>
			<li>7. 有料サービスにおいて，ユーザーに利用料金を請求するため</li>
			<li>8. 上記の利用目的に付随する目的</li>
		</ul>
	<h4>第4条（利用目的の変更）</h4>
	<ul>
		<li>1. 当社は，利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。</li>
		<li>2. 利用目的の変更を行った場合には，変更後の目的について，当社所定の方法により，ユーザーに通知し，または本ウェブサイト上に公表するものとします。</li>
	</ul>
	<h4>第5条（個人情報の第三者提供）</h4>
	<ul>
		<li>1. 当社は，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。</li>
			<ul class="hierarchy">
				<li>1. 人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき</li>
				<li>2. 公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき</li>
				<li>3. 国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき</li>
				<li>4. 予め次の事項を告知あるいは公表し，かつ当社が個人情報保護委員会に届出をしたとき</li>
					<ul class="hierarchy">
						<li>1. 利用目的に第三者への提供を含むこと</li>
						<li>2. 第三者に提供されるデータの項目</li>
						<li>3. 第三者への提供の手段または方法</li>
						<li>4. 本人の求めに応じて個人情報の第三者への提供を停止すること</li>
						<li>5. 本人の求めを受け付ける方法</li>
					</ul>
			</ul>
		<li>2. 前項の定めにかかわらず，次に掲げる場合には，当該情報の提供先は第三者に該当しないものとします。</li>
			<ul class="hierarchy">
				<li>1. 当社が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合</li>
				<li>2. 合併その他の事由による事業の承継に伴って個人情報が提供される場合</li>
				<li>3. 個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いた場合</li>
			</ul>
	</ul>
	<h4>第6条（個人情報の開示）</h4>
	<ul>
		<li>1. 当社は，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。なお，個人情報の開示に際しては，1件あたり1，000円の手数料を申し受けます。</li>
			<ul class="hierarchy">
				<li>1. 本人または第三者の生命，身体，財産その他の権利利益を害するおそれがある場合</li>
				<li>2. 当社の業務の適正な実施に著しい支障を及ぼすおそれがある場合</li>
				<li>3. その他法令に違反することとなる場合</li>
			</ul>
		<li>2. 前項の定めにかかわらず，履歴情報および特性情報などの個人情報以外の情報については，原則として開示いたしません。</li>
	</ul>
	<h4>第7条（個人情報の訂正および削除）</h4>
	<ul>
		<li>1. ユーザーは，当社の保有する自己の個人情報が誤った情報である場合には，当社が定める手続きにより，当社に対して個人情報の訂正，追加または削除（以下，「訂正等」といいます。）を請求することができます。</li>
		<li>2. 当社は，ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正等を行うものとします。</li>
		<li>3. 当社は，前項の規定に基づき訂正等を行った場合，または訂正等を行わない旨の決定をしたときは遅滞なく，これをユーザーに通知します。</li>
	</ul>
	<h4>第8条（個人情報の利用停止等）</h4>
	<ul>
		<li>1. 当社は，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行います。</li>
		<li>2. 前項の調査結果に基づき，その請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の利用停止等を行います。</li>
		<li>3. 当社は，前項の規定に基づき利用停止等を行った場合，または利用停止等を行わない旨の決定をしたときは，遅滞なく，これをユーザーに通知します。</li>
		<li>4. 前2項にかかわらず，利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じるものとします。</li>
	</ul>
	<h4>第9条（プライバシーポリシーの変更）</h4>
	<ul>
		<li>1. 本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。</li>
		<li>2. 当社が別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。</li>
	</ul>
	<h4>第10条（お問い合わせ窓口）</h4>
	<p>ご意見、ご質問、苦情のお申し出その他利用情報に関するお問い合わせは，下記メールアドレスまでお願いいたします。</p>
	<p>
		Sauna&Camp公式メールアドレス<br>
		saunacamp.official@gmail.com
	</p>
	<p class="terms-last">以上</p>
</div>

app/views/home/terms.html.erb
<div class="terms">
	<h3>利用規約</h3>
	<p>この利用規約（以下，「本規約」といいます。）は，Sauna&Camp（以下，「当社」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。</p>
	<h4>第1条（適用）</h4>
	<ul>
		<li>1. 本規約は，ユーザーと当社との間の本サービスの利用に関わる一切の関係に適用されるものとします</li>
		<li>2. 当社は本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。</li>
		<li>3. 本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。</li>
	</ul>
	<h4>第2条（利用登録）</h4>
	<ul>
		<li>1. 本サービスにおいては，登録希望者が本規約に同意の上，当社の定める方法によって利用登録を申請し，当社がこの承認を登録希望者に通知することによって，利用登録が完了するものとします。</li>
		<li>2. 当社は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。</li>
			<ul class="hierarchy">
				<li>1. 利用登録の申請に際して虚偽の事項を届け出た場合</li>
				<li>2. 本規約に違反したことがある者からの申請である場合</li>
				<li>3. その他，当社が利用登録を相当でないと判断した場合</li>
			</ul>
	</ul>
	<h4>第3条（ユーザーIDおよびパスワードの管理）</h4>
		<ul>
			<li>1. ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを適切に管理するものとします。</li>
			<li>2. ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与し，もしくは第三者と共用することはできません。当社は，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。</li>
			<li>3. ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は，当社に故意又は重大な過失がある場合を除き，当社は一切の責任を負わないものとします。</li>
		</ul>
	<h4>第4条（利用料金および支払方法）</h4>
	<ul>
		<li>1. ユーザーは，本サービスの有料部分の対価として，当社が別途定め，本ウェブサイトに表示する利用料金を，当社が指定する方法により支払うものとします。</li>
		<li>2. ユーザーが利用料金の支払を遅滞した場合には，ユーザーは年14．6％の割合による遅延損害金を支払うものとします。</li>
	</ul>
	<h4>第5条（禁止事項）</h4>
	<p>ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。</p>
	<ul class="hierarchy">
		<li>1. 法令または公序良俗に違反する行為</li>
		<li>2. 犯罪行為に関連する行為</li>
		<li>3. 当社，本サービスの他のユーザー，または第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</li>
		<li>4. 当社のサービスの運営を妨害するおそれのある行為</li>
		<li>5. 他のユーザーに関する個人情報等を収集または蓄積する行為</li>
		<li>6. 不正アクセスをし，またはこれを試みる行為</li>
		<li>7. 他のユーザーに成りすます行為</li>
		<li>8. 当社のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為</li>
		<li>9. 当社，本サービスの他のユーザーまたは第三者の知的財産権，肖像権，プライバシー，名誉その他の権利または利益を侵害する行為</li>
		<li>10. 以下の表現を含み，または含むと当社が判断する内容を本サービス上に投稿し，または送信する行為</li>
			<ul class="hierarchy">
				<li>1. 過度に暴力的な表現</li>
				<li>2. 露骨な性的表現</li>
				<li>3. 人種，国籍，信条，性別，社会的身分，門地等による差別につながる表現</li>
				<li>4. 自殺，自傷行為，薬物乱用を誘引または助長する表現</li>
				<li>5. その他反社会的な内容を含み他人に不快感を与える表現</li>
			</ul>
		<li>11. 以下を目的とし，または目的とすると当社が判断する行為</li>
			<ul class="hierarchy">
				<li>1. 営業，宣伝，広告，勧誘，その他営利を目的とする行為（当社の認めたものを除きます。）</li>
				<li>2. 性行為やわいせつな行為を目的とする行為</li>
				<li>3. 面識のない異性との出会いや交際を目的とする行為</li>
				<li>4. 他のユーザーに対する嫌がらせや誹謗中傷を目的とする行為</li>
				<li>5. 当社，本サービスの他のユーザー，または第三者に不利益，損害または不快感を与えることを目的とする行為</li>
				<li>6. その他本サービスが予定している利用目的と異なる目的で本サービスを利用する行為</li>
			</ul>
		<li>12. 宗教活動または宗教団体への勧誘行為</li>
		<li>13. その他，当社が不適切と判断する行為</li>
	</ul>
	<h4>第6条（本サービスの提供の停止等）</h4>
	<ul>
		<li>1. 当社は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。</li>
			<ul class="hierarchy">
				<li>1. 本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
				<li>2. 地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合</li>
				<li>3. コンピュータまたは通信回線等が事故により停止した場合</li>
				<li>4. その他，当社が本サービスの提供が困難と判断した場合</li>
			</ul>
		<li>2. 当社は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。</li>
	</ul>
	<h4>第7条（著作権）</h4>
	<ul>
		<li>1. ユーザーは，自ら著作権等の必要な知的財産権を有するか，または必要な権利者の許諾を得た文章，画像や映像等の情報に関してのみ，本サービスを利用し，投稿ないしアップロードすることができるものとします。</li>
		<li>2. ユーザーが本サービスを利用して投稿ないしアップロードした文章，画像，映像等の著作権については，当該ユーザーその他既存の権利者に留保されるものとします。ただし，当社は，本サービスを利用して投稿ないしアップロードされた文章，画像，映像等について，本サービスの改良，品質の向上，または不備の是正等ならびに本サービスの周知宣伝等に必要な範囲で利用できるものとし，ユーザーは，この利用に関して，著作者人格権を行使しないものとします。</li>
		<li>3. 前項本文の定めるものを除き，本サービスおよび本サービスに関連する一切の情報についての著作権およびその他の知的財産権はすべて当社または当社にその利用を許諾した権利者に帰属し，ユーザーは無断で複製，譲渡，貸与，翻訳，改変，転載，公衆送信（送信可能化を含みます。），伝送，配布，出版，営業使用等をしてはならないものとします。</li>
	</ul>
	<h4>第8条（利用制限および登録抹消）</h4>
	<ul>
		<li>1. 当社は，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，投稿データを削除し，ユーザーに対して本サービスの全部もしくは一部の利用を制限しまたはユーザーとしての登録を抹消することができるものとします。</li>
			<ul class="hierarchy">
				<li>1. 本規約のいずれかの条項に違反した場合</li>
				<li>2. 登録事項に虚偽の事実があることが判明した場合</li>
				<li>3. 決済手段として当該ユーザーが届け出たクレジットカードが利用停止となった場合</li>
				<li>4. 料金等の支払債務の不履行があった場合</li>
				<li>5. 当社からの連絡に対し，一定期間返答がない場合</li>
				<li>6. 本サービスについて，最終の利用から一定期間利用がない場合</li>
				<li>7. その他，当社が本サービスの利用を適当でないと判断した場合</li>
			</ul>
		<li>2. 前項各号のいずれかに該当した場合，ユーザーは，当然に当社に対する一切の債務について期限の利益を失い，その時点において負担する一切の債務を直ちに一括して弁済しなければなりません。</li>
		<li>3. 当社は，本条に基づき当社が行った行為によりユーザーに生じた損害について，一切の責任を負いません。</li>
	</ul>
	<h4>第9条（退会）</h4>
	<p>ユーザーは，当社の定める退会手続により，本サービスから退会できるものとします。</p>
	<h4>第10条（保証の否認および免責事項）</h4>
	<ul>
		<li>1. 当社は，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。</li>
		<li>2. 当社は，本サービスに起因してユーザーに生じたあらゆる損害について、当社の故意又は重過失による場合を除き、一切の責任を負いません。ただし，本サービスに関する当社とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。</li>
		<li>3. 前項ただし書に定める場合であっても，当社は，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（当社またはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。また，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は，ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。</li>
		<li>4. 当社は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。</li>
	</ul>
	<h4>第11条（サービス内容の変更等）</h4>
	<p>当社は，ユーザーへの事前の告知をもって、本サービスの内容を変更、追加または廃止することがあり、ユーザーはこれを承諾するものとします。</p>
	<h4>第12条（利用規約の変更）</h4>
	<ul>
		<li>1. 当社は以下の場合には、ユーザーの個別の同意を要せず、本規約を変更することができるものとします。</li>
			<ul class="hierarchy">
				<li>1. 本規約の変更がユーザーの一般の利益に適合するとき。</li>
				<li>2. 本規約の変更が本サービス利用契約の目的に反せず、かつ、変更の必要性、変更後の内容の相当性その他の変更に係る事情に照らして合理的なものであるとき。</li>
			</ul>
		<li>2. 当社はユーザーに対し、前項による本規約の変更にあたり、事前に、本規約を変更する旨及び変更後の本規約の内容並びにその効力発生時期を通知します。</li>
	</ul>
	<h4>第13条（個人情報の取扱い）</h4>
	<p>当社は，本サービスの利用によって取得する個人情報については，当社「プライバシーポリシー」に従い適切に取り扱うものとします。</p>
	<h4>第14条（通知または連絡）</h4>
	<p>ユーザーと当社との間の通知または連絡は，当社の定める方法によって行うものとします。当社は,ユーザーから,当社が別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。</p>
	<h4>第15条（権利義務の譲渡の禁止）</h4>
	<p>ユーザーは，当社の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。</p>
	<h4>第16条（準拠法・裁判管轄）</h4>
	<ul>
		<li>1. 本規約の解釈にあたっては，日本法を準拠法とします。</li>
		<li>2. 本サービスに関して紛争が生じた場合には，当社の本店所在地を管轄する裁判所を専属的合意管轄とします。</li>
	</ul>
	<p class="terms-last">以上</p>
</div>

app/views/home/top.html.erb
<div class="main-container">
	<div class="first-view">
		<div class="form-area">
			<h1 class="home">SAUNA&CAMP</h1>
			<h5>お気に入りのサウナや自然スポットをシェアしてみませんか？</h5>
			<% unless user_signed_in? %>
				<%= link_to "登録してみる", new_user_registration_path, class: "btn btn-success" %>
				<%= link_to "ログイン", new_user_session_path, class: "btn btn-success" %>
			<% end %>
			<%= search_form_for @search, url: search_saunas_path do |f| %>
				<%= f.text_field :address_cont, id: "search-address", class: 'form-control', placeholder: '地域を入力' %>
			<% end %>
		</div>
	</div>
	<div class="second-view">
		<%= render "home/ranking", sauna_favorite_ranks: @sauna_favorite_ranks %>
	</div>
</div>