config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root to: "home#top"
  get "about" => "home#about"
  get "terms" => "home#terms"
  get "policy" => "home#policy"
  get "users/:id/favorites" => "users#favorites"
  resources :users
  resources :saunas do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get :search
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/sauna.rb
class Sauna < ApplicationRecord
  has_one_attached :avatar
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  has_many :comments, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  with_options presence: true do
    validates :name
    validates :privacy
  end

  scope :latest, -> { order(created_at: :desc) }
  scope :old, -> { order(created_at: :asc) }
  scope :name_order, -> { order(name: :desc) }
end

app/controllers/saunas_controller.rb
class SaunasController < ApplicationController
  before_action :set_q, only: [:index, :search]
  before_action :authenticate_user!, except: [:index, :show, :search]

  def index
    if params[:latest]
      @saunas = Sauna.latest.page(params[:page]).per(15).includes(:user)
    elsif params[:old]
      @saunas = Sauna.old.page(params[:page]).per(15).includes(:user)
    elsif params[:name]
      @saunas = Sauna.name_order.page(params[:page]).per(15).includes(:user)
    else
      @saunas = Sauna.all.page(params[:page]).per(15).includes(:user)
    end
  end

  def show
    @sauna = Sauna.find_by(id: params[:id])
    @comment = Comment.new
    @comments = @sauna.comments.includes(:user)
    if (@sauna.privacy == "2") && (@sauna.user_id != current_user.id)
      redirect_back fallback_location: saunas_path
      flash[:alert] = "非公開に設定されているサウナのため閲覧できません"
    end
  end

  def new
    @sauna = Sauna.new
  end

  def create
    @sauna = Sauna.new(sauna_params)
    @sauna.user_id = current_user.id
    if @sauna.save
      redirect_to sauna_path(@sauna)
      flash[:notice] = "#{@sauna.name}を投稿しました"
    else
      render :new
    end
  end

  def edit
    @sauna = Sauna.find_by(id: params[:id])
    if @sauna.user != current_user
      redirect_to sauna_path(@sauna)
      flash[:alert] = "不正なアクセスです"
    end
    if (@sauna.privacy == "2") && (@sauna.user_id != current_user.id)
      redirect_back fallback_location: saunas_path
      flash[:alert] = "非公開に設定されているサウナのため編集できません"
    end
  end

  def update
    @sauna = Sauna.find_by(id: params[:id])
    if @sauna.update(sauna_params)
      redirect_to sauna_path(@sauna)
      flash[:notice] = "#{@sauna.name}を編集しました"
    else
      render :edit
    end
  end

  def destroy
    @sauna = Sauna.find_by(id: params[:id])
    @sauna.destroy
    redirect_to saunas_path
    flash[:notice] = "#{@sauna.name}を削除しました"
  end

  def search
    @saunas = Sauna.all
  end

  private

  def set_q
    @q = Sauna.ransack(params[:q])
  end

  def sauna_params
    params.require(:sauna).permit(:name, :image, :water_temperature, :open_time, :close_time,
    :sauna_temperature, :sauna_capacity, :water_capacity, :sauna_body, :water_body, :louly_aufgoose,
    :louly_body, :rest_space, :rest_body, :address, :access, :tel, :price, :http, :latitude, :longitude, :privacy, :avatar)
  end
end

app/helpers/saunas_helper.rb
module SaunasHelper
end

app/views/saunas/_comments.html.erb
<% if user_signed_in? %>
	<div class="container">
		<div class="row">
			<div class="col-xl-12 my-5">
				<div class="card shadow rounded">
					<div class="card-header text-center">
						<h4>口コミ</h4>
					</div>
					<%= form_with(model: [sauna, comment], local: true) do |f| %>
						<%= f.text_area :content, class: "form-control", rows: 5, placeholder: "口コミを入力する" %>
						<%= button_tag type: "submit", class: "btn btn-success float-right" do %>
							<i class="far fa-comments"></i> コメントする
						<% end %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
<% end %>
<div class="container">
	<div class="row">
		<div class="col-xl-12 my-5">
			<div class="card shadow rounded">
				<div class="card-header text-center">
					<h4>口コミ一覧</h4>
				</div>
				<% comments.each do |comment| %>
					<div class="review-index">
						<% unless comment.user.blank? %>
							<%= link_to user_path(comment.user_id) do %>
								<% if comment.user.avatar.attached? %>
									<%= image_tag comment.user.avatar, class: "icon" %>
								<% else %>
									<%= image_tag "no-image.png", class: "icon" %>
								<% end %>
								<%= comment.user.name unless comment.user.blank? %>
							<% end %>
						<% end %>
						<p class="comment-day">
							<%= comment.created_at.strftime("%Y年%m月%d日 %H:%M") %>
						</p>
						<br />
						<%= comment.content %>
						<% if (user_signed_in?) && (comment.user_id == current_user.id) %>
							<%= link_to "口コミを削除する", sauna_comment_path(sauna, comment), data: {confirm: "口コミを削除しますか？"}, method: :delete, class: "btn btn-sm btn-danger float-right" %>
						<% end %>
						<br />
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/saunas/_information.html.erb
<div class="col-xl-8 col-12 mt-5">
	<div class="card shadow rounded">
		<div class="card-header">
			<h4>詳細情報</h4>
		</div>
		<div class="card-body show-card-body">
			<p class="select-genre mt-4 mb-2">
				<i class="far fa-circle fa-fw"></i>営業情報
			</p>
		</div>
		<% if sauna.address.present? %>
			<div class="row mb-1">
				<div class="col-sm-4 col-6 text-left pl-4">
					<i class="fas fa-map-marker-alt fa-fw"></i>住所
				</div>
				<div class="col-sm-8 col-6 text-left">
					<%= sauna.address %>
				</div>
			</div>
		<% end %>
		<% if sauna.http.present? %>
			<div class="row mb-1">
				<div class="col-sm-4 col-6 text-left pl-4">
					<i class="fas fa-map-marker-alt fa-fw"></i>ホームページ
				</div>
				<div class="col-sm-8 col-6 text-left">
					<%= link_to sauna.http, sauna.http, target: '_blank' %>
				</div>
			</div>
		<% end %>
		<% if sauna.tel.present? %>
			<div class="row mb-1">
				<div class="col-sm-4 col-6 text-left pl-4">
					<i class="fas fa-phone fa-fw"></i>電話番号
				</div>
				<div class="col-sm-8 col-6 text-left">
					<%= sauna.tel %>
				</div>
			</div>
		<% end %>
		<% if sauna.price.present? %>
			<div class="row mb-1">
				<div class="col-sm-4 col-6 text-left pl-4">
					<i class="fas fa-phone fa-fw"></i>料金
				</div>
				<div class="col-sm-8 col-6 text-left">
					<%= sauna.price %>
				</div>
			</div>
		<% end %>
		<% if sauna.open_time.present? %>
			<div class="row mb-1">
				<div class="col-sm-4 col-6 text-left pl-4">
					<i class="fas fa-hourglass-start fa-fw"></i>開店時間
				</div>
				<div class="col-sm-8 col-6 text-left">
					<%= sauna.open_time.strftime("%H:%M") %>
				</div>
			</div>
		<% end %>
		<% if sauna.close_time.present? %>
			<div class="row mb-1">
				<div class="col-sm-4 col-6 text-left pl-4">
					<i class="fas fa-hourglass-end fa-fw"></i>閉店時間
				</div>
				<div class="col-sm-8 col-6 text-left">
					<%= sauna.close_time.strftime("%H:%M") %>
				</div>
			</div>
		<% end %>
		<% if sauna.access.present? %>
			<div class="row mb-1">
				<div class="col-sm-4 col-6 text-left pl-4">
					<i class="fas fa-walking fa-fw"></i>アクセス
				</div>
				<div class="col-sm-8 col-6 text-left">
					<%= sauna.access %>
				</div>
			</div>
		<% end %>
		<div class="card-body show-card-body">
			<p class="select-genre mt-4 mb-2">
				<i class="far fa-circle fa-fw"></i>施設情報
			</p>
		</div>
		<% if sauna.sauna_temperature.present? %>
			<div class="row mb-1">
				<div class="col-sm-4 col-6 text-left pl-4">
					<i class="fas fa-temperature-high fa-fw"></i>サウナ温度
				</div>
				<div class="col-sm-8 col-6 text-left">
					<%= sauna.sauna_temperature %>℃
				</div>
			</div>
		<% end %>
		<% if sauna.sauna_capacity.present? %>
			<div class="row mb-1">
				<div class="col-sm-4 col-6 text-left pl-4">
					<i class="fas fa-user-alt fa-fw"></i>サウナ収容人数
				</div>
				<div class="col-sm-8 col-6 text-left">
					<%= sauna.sauna_capacity %>人
				</div>
			</div>
		<% end %>
		<% if sauna.sauna_body.present? %>
			<div class="row mb-1">
				<div class="col-sm-4 col-6 text-left pl-4">
					<i class="fas fa-hot-tub fa-fw"></i>サウナ詳細
				</div>
				<div class="col-sm-8 col-6 text-left">
					<%= sauna.sauna_body %>
				</div>
			</div>
		<% end %>
		<% if sauna.water_temperature.present? %>
			<div class="row mb-1">
				<div class="col-sm-4 col-6 text-left pl-4">
					<i class="fas fa-temperature-low fa-fw"></i>水風呂温度
				</div>
				<div class="col-sm-8 col-6 text-left">
					<%= sauna.water_temperature %>℃
				</div>
			</div>
		<% end %>
		<% if sauna.water_capacity.present? %>
			<div class="row mb-1">
				<div class="col-sm-4 col-6 text-left pl-4">
					<i class="fas fa-user-alt fa-fw"></i>水風呂収容人数
				</div>
				<div class="col-sm-8 col-6 text-left">
					<%= sauna.water_capacity %>人
				</div>
			</div>
		<% end %>
		<% if sauna.water_body.present? %>
			<div class="row mb-1">
				<div class="col-sm-4 col-6 text-left pl-4">
					<i class="fas fa-tint fa-fw"></i>水風呂詳細
				</div>
				<div class="col-sm-8 col-6 text-left">
					<%= sauna.water_body %>
				</div>
			</div>
		<% end %>
		<% if sauna.louly_aufgoose.present? %>
			<div class="row mb-1">
				<div class="col-sm-4 col-6 text-left pl-4">
					<i class="fas fa-wind fa-fw"></i>ロウリュ・アウフグースサービス
				</div>
				<div class="col-sm-8 col-6 text-left">
					<% if sauna.louly_aufgoose == true %>
						有
					<% else %>
						無
					<% end %>
				</div>
			</div>
		<% end %>
		<% if (sauna.louly_aufgoose == true) && (sauna.louly_body.present?) %>
			<div class="row mb-1">
				<div class="col-sm-4 col-6 text-left pl-4">
					<i class="fas fa-info-circle fa-fw"></i>ロウリュ・アウフグースサービス詳細
				</div>
				<div class="col-sm-8 col-6 text-left">
					<%= sauna.louly_body %>
				</div>
			</div>
		<% end %>
		<% if sauna.rest_space.present? %>
			<div class="row mb-1">
				<div class="col-sm-4 col-6 text-left pl-4">
					<i class="fas fa-chair fa-fw"></i>休憩スペース
				</div>
				<div class="col-sm-8 col-6 text-left">
					<% if sauna.rest_space == true %>
						有
					<% else %>
						無
					<% end %>
				</div>
			</div>
		<% end %>
		<% if (sauna.rest_space == true) && (sauna.rest_body.present?) %>
			<div class="row mb-1">
				<div class="col-sm-4 col-6 text-left pl-4">
					<i class="fas fa-info-circle fa-fw"></i>休憩スペース詳細
				</div>
				<div class="col-sm-8 col-6 text-left">
					<%= sauna.rest_body %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/saunas/_map.html.erb
<div class="container">
	<div class="row">
		<div class="col-xl-12 my-5">
			<div class="card shadow rounded">
				<div class="card-header text-center">
					<h4>マップ</h4>
				</div>
				<div class="content">
					<div id="map"></div>
					<%= link_to "GoogleMapで開く", "https://maps.google.co.jp/maps?q=loc:#{sauna.latitude},#{sauna.longitude}&iwloc=J", target: "_blank", class: "btn btn-sm btn-primary float-right" %>
				</div>
				<script type="text/javascript">
					function initMap() {
						var test ={lat: <%= sauna.latitude %>, lng: <%= sauna.longitude %>};
						var map = new google.maps.Map(document.getElementById('map'), {
								zoom: 15,
								center: test
						});
						var transitLayer = new google.maps.TransitLayer();
						transitLayer.setMap(map);
						var contentString = '住所：<%= sauna.address %>';
						var infowindow = new google.maps.InfoWindow({
								content: contentString
						});
						var marker = new google.maps.Marker({
								position:test,
								map: map,
								title: contentString
						});
						marker.addListener('click', function() {
								infowindow.open(map, marker);
						});
					}
				</script>
				<script async defer
					src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyB0o3pN3_ivrmhUe14CgAGcp9aAsl3g_6c&callback=initMap">
				</script>
				<style type="text/css">
					#map { 
						height: 400px;
						margin-left:auto;
						margin-right:auto;
						text-align:left;
						width: 100%;
					}
				</style>
			</div>
		</div>
	</div>
</div>

app/views/saunas/_sns.html.erb
<%= link_to "https://twitter.com/share?url=#{request.url}/&text=#{@sauna.name}/&hashtags=SaunaCamp", class: 'twitter', target: '_blank' do %>
	<i class="fab fa-twitter" style='color: #3399FF;'></i>ツイートする
<% end %>
<div class="fb-share-button" data-layout="button" data-size="small"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=<%= request.url %>" class="fb-xfbml-parse-ignore">シェアする</a></div>
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v15.0" nonce="zNL9Srtm"></script>

app/views/saunas/edit.html.erb
<% provide(:title, @sauna.name) %>
<div class="row">
  <div class="col-md-12">
		<% @sauna.errors.full_messages.each do |message| %>
			<div class="errors_message">
				<%= message %>
			</div>
    <% end %>
		<%= form_with model: @sauna do |f| %>
			<div class="card" style="width: 54rem;">
				<div class="card-header">サウナ登録画面</div>
				<ul class="list-group list-group-flush">
					<li class="list-group-item">
						<label for="privacy">公開・非公開</label><div class="body-of-label"><%= f.select :privacy, [["公開", 1], ["非公開", 2]], include_blank: "選択して下さい" %></div>
					</li>
					<li class="list-group-item">
						<label for="name">サウナ名</label><div class="body-of-label"><%= f.text_field :name, class: "form-control", placeholder: @sauna.name %></div>
					</li>
					<li class="list-group-item">
						<label for="image">サウナ画像</label><div class="body-of-label"><%= f.file_field :avatar, placeholder: "画像を選択" %></div>
					</li>
					<li class="list-group-item">
						<label for="address">住所</label><%= f.text_field :address, class: "form-control", placeholder: @sauna.address %>
					</li>
					<li class="list-group-item">
						<label for="http">ホームページ</label><%= f.text_field :http, class: "form-control", placeholder: @sauna.http %>
					</li>
					<li class="list-group-item">
						<label for="price">料金</label><%= f.text_field :price, class: "form-control", placeholder: @sauna.price %>
					</li>
					<li class="list-group-item">
						<label for="access">アクセス</label><div class="body-of-label"><%= f.text_area :access, class: "form-control", placeholder: @sauna.access %></div>
					</li>
					<li class="list-group-item">
						<label for="tel">電話番号</label><%= f.telephone_field :tel, class: "form-control", placeholder: @sauna.tel %>
					</li>
					<li class="list-group-item">
						<label for="open_time">開店時間</label><%= f.time_select :open_time, class: "form-control", placeholder: @sauna.open_time %>
					</li>
					<li class="list-group-item">
						<label for="close_time">閉店時間</label><%= f.time_select :close_time, class: "form-control", placeholder: @sauna.close_time %>
					</li>
					<li class="list-group-item">
						<label for="sauna_temperature">サウナの温度(℃)</label><%= f.number_field :sauna_temperature, class: "form-control", placeholder: @sauna.sauna_temperature %>
					</li>
					<li class="list-group-item">
						<label for="water_temperature">水風呂の温度(℃)</label><%= f.number_field :water_temperature, class: "form-control", placeholder: @sauna.water_temperature %>
					</li>
					<li class="list-group-item">
						<label for="sauna_capacity">サウナの収容人数(人)</label><%= f.number_field :sauna_capacity, class: "form-control", placeholder: @sauna.sauna_capacity %>
					</li>
					<li class="list-group-item">
						<label for="water_capacity">水風呂の収容人数(人)</label><%= f.number_field :water_capacity, class: "form-control", placeholder: @sauna.water_capacity %>
					</li>
					<li class="list-group-item">
						<label for="sauna_body">サウナ詳細</label><div class="body-of-label"><%= f.text_area :sauna_body, class: "form-control", placeholder: @sauna.sauna_body %></div>
					</li>
					<li class="list-group-item">
						<label for="water_body">水風呂詳細</label><div class="body-of-label"><%= f.text_area :water_body, class: "form-control", placeholder: @sauna.water_body %></div>
					</li>
					<li class="list-group-item">
						<label for="louly_aufgoose">ロウリュ・アウフグースサービスの有無</label><%= f.check_box :louly_aufgoose, {}, checked: true, unchecked: false %>
					</li>
					<li class="list-group-item">
						<label for="louly_body">ロウリュ・アウフグースサービス詳細</label><%= f.text_area :louly_body, class: "form-control", placeholder: @sauna.louly_body %>
					</li>
					<li class="list-group-item">
						<label for="rest_space">休憩スペースの有無</label><%= f.check_box :rest_space, {}, checked: true, unchecked: false %>
					</li>
					<li class="list-group-item">
						<label for="rest_body">休憩スペース詳細</label><%= f.text_area :rest_body, class: "form-control", placeholder: @sauna.rest_body %>
					</li>
					<li class="list-group-item">
						<input type="submit" value="修正する" class="btn btn-sm btn-info">
						<%= link_to "戻る", sauna_path(@sauna.id), class: "btn btn-sm btn-info" %>
					</li>
				</ul>
			</div>
		<% end %>
	</div>
</div>

app/views/saunas/index.html.erb
<div class="container">
	<div class="contents-title text-center">
		<h3 class="index-title">
			サウナ一覧
			<div class="btn-group">
			<button class="btn btn-secondary btn-success dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				並び順
			</button>
			<div class="dropdown-menu">
				<li class="dropdown-item"><%= link_to "新しい順", saunas_path(latest: "true") %></li>
				<li class="dropdown-item"><%= link_to "古い順", saunas_path(old: "true") %></li>
				<li class="dropdown-item"><%= link_to "名前順", saunas_path(name: "true") %></li>
			</div>
		</div>
		</h3>
	</div>
	<div class="row">
		<% @saunas.with_attached_avatar.each do |sauna| %>
			<% if sauna.privacy == "1" %>
				<div class="col-md-4">
					<div class="card">
						<% if sauna.avatar.attached? %>
							<%= image_tag sauna.avatar, class: "card-img-top" %>
						<% else %>
							<%= image_tag "no-image.png", class: "card-img-top" %>
						<% end %>
						<div class="card-body text-center">
							<h5 class="card-title"><%= sauna.name %></h5>
							<div class="author">
								<% if sauna.user.avatar.attached? %>
									<%= image_tag sauna.user.avatar, class: "icon" %>
								<% else %>
									<%= image_tag "no-image.png", class: "icon" %>
								<% end %>
								投稿者:<%= link_to sauna.user.name, user_path(sauna.user_id) %>
							</div>
							<%= link_to "詳細を見る", sauna_path(sauna.id), class: "btn btn-info" %>
						</div>
					</div>
				</div>
			<% elsif (user_signed_in?) && (sauna.user_id == current_user.id) && (sauna.privacy == "2") %>
				<div class="col-md-4">
					<div class="card">
						<% if sauna.avatar.attached? %>
							<%= image_tag sauna.avatar, class: "card-img-top" %>
						<% else %>
							<%= image_tag "no-image.png", class: "card-img-top" %>
						<% end %>
						<div class="card-body text-center">
							<h5 class="card-title"><%= sauna.name %>(非公開)</h5>
							<div class="author">
								<% if sauna.user.avatar.attached? %>
									<%= image_tag sauna.user.avatar, class: "icon" %>
								<% else %>
									<%= image_tag "no-image.png", class: "icon" %>
								<% end %>
								投稿者:<%= link_to sauna.user.name, user_path(sauna.user_id) %>
							</div>
							<%= link_to "詳細を見る", sauna_path(sauna.id), class: "btn btn-info" %>
						</div>
					</div>
				</div>
			<% end %>
		<% end %>
	</div>
	<%= paginate @saunas %>
</div> 

app/views/saunas/new.html.erb
<div class="row">
  <div class="col-md-12">
		<% @sauna.errors.full_messages.each do |message| %>
			<div class="errors_message">
				<%= message %>
			</div>
    <% end %>
		<%= form_with model: @sauna do |f| %>
			<div class="card" style="width: 54rem;">
				<div class="card-header">新規サウナ登録画面</div>
				<ul class="list-group list-group-flush">
					<li class="list-group-item">
						<label for="privacy">公開・非公開(必須)</label><div class="body-of-label"><%= f.select :privacy, [["公開", 1], ["非公開", 2]], include_blank: "選択して下さい" %></div>
					</li>
					<li class="list-group-item">
						<label for="name">サウナ名(必須)</label><div class="body-of-label"><%= f.text_field :name, class: "form-control" %></div>
					</li>
					<li class="list-group-item">
						<label for="image">サウナ画像</label><div class="body-of-label"><%= f.file_field :avatar, placeholder: "画像を選択" %></div>
					</li>
					<li class="list-group-item">
						<label for="address">住所</label><%= f.text_field :address, class: "form-control" %>
					</li>
					<li class="list-group-item">
						<label for="http">ホームページ</label><%= f.text_field :http, class: "form-control" %>
					</li>
					<li class="list-group-item">
						<label for="price">料金</label><%= f.text_field :price, class: "form-control" %>
					</li>
					<li class="list-group-item">
						<label for="access">アクセス</label><div class="body-of-label"><%= f.text_area :access, class: "form-control" %></div>
					</li>
					<li class="list-group-item">
						<label for="tel">電話番号</label><%= f.telephone_field :tel, class: "form-control" %>
					</li>
					<li class="list-group-item">
						<label for="open_time">開店時間</label><%= f.time_select :open_time, class: "form-control" %>
					</li>
					<li class="list-group-item">
						<label for="close_time">閉店時間</label><%= f.time_select :close_time, class: "form-control" %>
					</li>
					<li class="list-group-item">
						<label for="sauna_temperature">サウナの温度(℃)</label><%= f.number_field :sauna_temperature, class: "form-control" %>
					</li>
					<li class="list-group-item">
						<label for="water_temperature">水風呂の温度(℃)</label><%= f.number_field :water_temperature, class: "form-control" %>
					</li>
					<li class="list-group-item">
						<label for="sauna_capacity">サウナの収容人数(人)</label><%= f.number_field :sauna_capacity, class: "form-control" %>
					</li>
					<li class="list-group-item">
						<label for="water_capacity">水風呂の収容人数(人)</label><%= f.number_field :water_capacity, class: "form-control" %>
					</li>
					<li class="list-group-item">
						<label for="sauna_body">サウナ詳細</label><div class="body-of-label"><%= f.text_area :sauna_body, class: "form-control" %></div>
					</li>
					<li class="list-group-item">
						<label for="water_body">水風呂詳細</label><div class="body-of-label"><%= f.text_area :water_body, class: "form-control" %></div>
					</li>
					<li class="list-group-item">
						<label for="louly_aufgoose">ロウリュ・アウフグースサービスの有無</label><%= f.check_box :louly_aufgoose, {}, checked: true, unchecked: false %>
					</li>
					<li class="list-group-item">
						<label for="louly_body">ロウリュ・アウフグースサービス詳細</label><%= f.text_area :louly_body, class: "form-control" %>
					</li>
					<li class="list-group-item">
						<label for="rest_space">休憩スペースの有無</label><%= f.check_box :rest_space, {}, checked: true, unchecked: false %>
					</li>
					<li class="list-group-item">
						<label for="rest_body">休憩スペース詳細</label><%= f.text_area :rest_body, class: "form-control" %>
					</li>
					<li class="list-group-item">
						<input type="submit" value="サウナを登録する" class="btn btn-sm btn-info">
					</li>
				</ul>
			</div>
		<% end %>
	</div>
</div>

app/views/saunas/search.html.erb
<div class="container">
	<div class="contents-title text-center">
		<h3 class="index-title">
			検索結果:<%= @search_saunas.count %>件
		</h3>
		<% if @search_saunas.count == 0 %>
			<p>キーワードに当てはまるサウナはありませんでした</p>
		<% end %>
	</div>
	<div class="row">
		<% @search_saunas.with_attached_avatar.each do |sauna| %>
			<% if sauna.privacy == "1" %>
				<div class="col-md-4">
					<div class="card">
						<% if sauna.avatar.attached? %>
							<%= image_tag sauna.avatar, class: "card-img-top" %>
						<% else %>
							<%= image_tag "no-image.png", class: "card-img-top" %>
						<% end %>
						<div class="card-body text-center">
							<h5 class="card-title"><%= sauna.name %></h5>
							<%= link_to "詳細を見る", sauna_path(sauna.id), class: "btn btn-info" %>
						</div>
					</div>
				</div>
			<% elsif (sauna.privacy == "2") && (sauna.user_id == current_user.id) %>
				<div class="col-md-4">
					<div class="card">
						<% if sauna.avatar.attached? %>
							<%= image_tag sauna.avatar, class: "card-img-top" %>
						<% else %>
							<%= image_tag "no-image.png", class: "card-img-top" %>
						<% end %>
						<div class="card-body text-center">
							<h5 class="card-title"><%= sauna.name %>(非公開)</h5>
							<%= link_to "詳細を見る", sauna_path(sauna.id), class: "btn btn-info" %>
						</div>
					</div>
				</div>
			<% end %>
		<% end %>
	</div>
</div> 

app/views/saunas/show.html.erb
<% provide(:title, @sauna.name) %>
<div class="container">
  <div class="row">
    <div class="col-xl-4 col-12 mt-5">
      <div class="card shadow rounded">
        <div class="card-header">
          <h4 class="show-field-header">
            <%= @sauna.name %>
            <% if user_signed_in? %>
            <%= render "favorites/favorite", sauna: @sauna %>
            <% end %>
          </h4>
        </div>
        <% if @sauna.avatar.attached? %>
          <%= image_tag @sauna.avatar, class: "show-image" %>
        <% else %>
          <%= image_tag "no-image.png", class: "show-image" %>
        <% end %>
        <% if (user_signed_in?) && (@sauna.user_id == current_user.id) %>
          <%= link_to "#{@sauna.name}の情報を変更する", edit_sauna_path(@sauna), class: "btn btn-sm btn-success" %>
          <%= link_to "#{@sauna.name}を削除する", sauna_path(@sauna), method: :delete, data: { confirm: "#{@sauna.name}を削除しますか？" }, class: "btn btn-sm btn-danger" %>
        <% end %>
        <div class="card-body">
          <div class="d-flex justify-content-center">
            <%= render "saunas/sns" %>
          </div>
        </div>
      </div>
    </div>
    <%= render "saunas/information", sauna: @sauna %>
    <%= render "saunas/comments", sauna: @sauna, comment: @comment, comments: @comments %>
    <%= render "saunas/map", sauna: @sauna %>
  </div>
</div>