config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root to: "home#top"
  get "about" => "home#about"
  get "terms" => "home#terms"
  get "policy" => "home#policy"
  get "users/:id/favorites" => "users#favorites"
  resources :users
  resources :saunas do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get :search
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>
	<ul class="footer-menu">
		<li><%= link_to "Sauna&Campとは？", about_path, :class=> "top-page-link" %></li>
		<li><%= link_to "利用規約", terms_path, :class=> "top-page-link" %></li>
		<li><%= link_to "プライバシーポリシー", policy_path, :class=> "top-page-link" %></li>
	</ul>
	<p>© All rights reserved by Sauna&Camp
	</p>
</footer>

app/views/layouts/_header.html.erb
<header>
	<nav class="navbar navbar-expand-md navbar-dark bg-dark text-white">
		<% if user_signed_in? %>
			<%= link_to user_path(current_user) do %>
				<% if current_user.avatar.attached? %>
					<%= image_tag current_user.avatar, class: "icon" %>
				<% else %>
					<%= image_tag "no-image.png", class: "icon" %>
				<% end %>
			<% end %>
		<% end %>
		<li class="nav-list-item">
			<%= link_to root_path do %>
				<h5 class="home" style="font-family: cursive; color: white; transition-duration: 0.5s;" onMouseOut="this.style.color='white';" onMouseOver="this.style.color='#888'">Sauna&Camp</h5>
			<% end %>
		</li>
		<%= search_form_for @search, url: search_saunas_path do |f| %>
			<%= f.text_field :name_or_address_or_sauna_body_or_water_body_or_louly_body_cont, id: "search-form", class: 'form-control', placeholder: 'キーワードを入力' %>
		<% end %>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNavDropdown">
			<ul class="navbar-nav ml-auto">
				<% if user_signed_in? %>
					<div class="dropdown dropleft">
						<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							メニュー
						</button>
						<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
							<li class="nav-item">
								<%= link_to "About", about_path %>
							</li>
							<li class="nav-item">
								<%= link_to current_user.name, user_path(current_user) %>
							</li>
							<% if current_user.name != 'ゲストユーザー' %>
								<li class="nav-item">
									<%= link_to "プロフィール編集", edit_user_path(current_user) %>
								</li>
							<% end %>
							<li class="nav-item">
								<%= link_to "新規サウナ登録", new_sauna_path %>
							</li>
							<li class="nav-item">
								<%= link_to "サウナ一覧", saunas_path %>
							</li>
							<li class="nav-item">
								<%= link_to "お気に入りサウナ", "/users/#{current_user.id}/favorites" %>
							</li>
							<li class="nav-item">
								<%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" } %>
							</li>
						</div>
					</div>
				<% else %>
					<li class="nav-item">
						<%= link_to "About", about_path, :class=> "top-page-link" %>
					</li>
					<li class="nav-item">
						<%= link_to "サウナ一覧", saunas_path, :class=> "top-page-link" %>
					</li>
					<li class="nav-item">
						<%= link_to "新規登録", new_user_registration_path, :class=> "top-page-link" %>
					</li>
					<li class="nav-item">
						<%= link_to "ログイン", new_user_session_path, :class=> "top-page-link" %>
					</li>
					<li class="nav-item">
						<%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, :class=> "top-page-link" %>
					</li>
				<% end %>
			</ul>
		</div>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/header" %>
    <% if flash[:notice] %>
      <p class="flash"><%= notice %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="flash"><%= alert %></p>
    <% end %>
    <div class="saunacamp">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>